steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"

  - name: "gcr.io/google-cloud-sdk/slim"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image=$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region=$_DEPLOY_REGION"
      - "--platform=managed"
      - "--quiet"

images:
  - "$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"

substitutions:
  _AR_HOSTNAME: asia-southeast2-docker.pkg.dev
  _REPOSITORY: cloud-run-source-deploy
  _SERVICE_NAME: desa-digital-landing
  _DEPLOY_REGION: asia-southeast2

options:
  logging: CLOUD_LOGGING_ONLY
